"""Add logging and monitoring tables

Revision ID: 37aad88426c6
Revises: f64d40dd0fb0
Create Date: 2025-08-03 17:59:34.796434+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '37aad88426c6'
down_revision: Union[str, None] = 'f64d40dd0fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('body_size', sa.Integer(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_size', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_path_method', 'api_request_logs', ['path', 'method'], unique=False)
    op.create_index('idx_api_timestamp_status', 'api_request_logs', ['timestamp', 'response_status'], unique=False)
    op.create_index(op.f('ix_api_request_logs_client_ip'), 'api_request_logs', ['client_ip'], unique=False)
    op.create_index(op.f('ix_api_request_logs_id'), 'api_request_logs', ['id'], unique=False)
    op.create_index(op.f('ix_api_request_logs_request_id'), 'api_request_logs', ['request_id'], unique=True)
    op.create_index(op.f('ix_api_request_logs_response_status'), 'api_request_logs', ['response_status'], unique=False)
    op.create_index(op.f('ix_api_request_logs_timestamp'), 'api_request_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_api_request_logs_user_id'), 'api_request_logs', ['user_id'], unique=False)
    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('logger_name', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('function', sa.String(length=100), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.String(length=50), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('exception_type', sa.String(length=100), nullable=True),
    sa.Column('exception_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_logger_level', 'log_entries', ['logger_name', 'level'], unique=False)
    op.create_index('idx_log_request', 'log_entries', ['request_id'], unique=False)
    op.create_index('idx_log_timestamp_level', 'log_entries', ['timestamp', 'level'], unique=False)
    op.create_index(op.f('ix_log_entries_id'), 'log_entries', ['id'], unique=False)
    op.create_index(op.f('ix_log_entries_level'), 'log_entries', ['level'], unique=False)
    op.create_index(op.f('ix_log_entries_logger_name'), 'log_entries', ['logger_name'], unique=False)
    op.create_index(op.f('ix_log_entries_timestamp'), 'log_entries', ['timestamp'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('component', sa.String(length=100), nullable=True),
    sa.Column('operation', sa.String(length=100), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_perf_component_operation', 'performance_metrics', ['component', 'operation'], unique=False)
    op.create_index('idx_perf_timestamp_metric', 'performance_metrics', ['timestamp', 'metric_name'], unique=False)
    op.create_index(op.f('ix_performance_metrics_component'), 'performance_metrics', ['component'], unique=False)
    op.create_index(op.f('ix_performance_metrics_id'), 'performance_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_performance_metrics_metric_name'), 'performance_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_performance_metrics_timestamp'), 'performance_metrics', ['timestamp'], unique=False)
    op.create_table('system_health_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=True),
    sa.Column('memory_usage_bytes', sa.Integer(), nullable=True),
    sa.Column('memory_available_bytes', sa.Integer(), nullable=True),
    sa.Column('disk_usage_bytes', sa.Integer(), nullable=True),
    sa.Column('disk_available_bytes', sa.Integer(), nullable=True),
    sa.Column('network_bytes_sent', sa.Integer(), nullable=True),
    sa.Column('network_bytes_received', sa.Integer(), nullable=True),
    sa.Column('database_connections_active', sa.Integer(), nullable=True),
    sa.Column('database_connections_idle', sa.Integer(), nullable=True),
    sa.Column('database_query_avg_time_ms', sa.Float(), nullable=True),
    sa.Column('load_average', sa.Float(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_health_timestamp_type', 'system_health_metrics', ['timestamp', 'metric_type'], unique=False)
    op.create_index(op.f('ix_system_health_metrics_id'), 'system_health_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_system_health_metrics_metric_type'), 'system_health_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_system_health_metrics_timestamp'), 'system_health_metrics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_health_metrics_timestamp'), table_name='system_health_metrics')
    op.drop_index(op.f('ix_system_health_metrics_metric_type'), table_name='system_health_metrics')
    op.drop_index(op.f('ix_system_health_metrics_id'), table_name='system_health_metrics')
    op.drop_index('idx_health_timestamp_type', table_name='system_health_metrics')
    op.drop_table('system_health_metrics')
    op.drop_index(op.f('ix_performance_metrics_timestamp'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_metric_name'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_id'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_component'), table_name='performance_metrics')
    op.drop_index('idx_perf_timestamp_metric', table_name='performance_metrics')
    op.drop_index('idx_perf_component_operation', table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index(op.f('ix_log_entries_timestamp'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_logger_name'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_level'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_id'), table_name='log_entries')
    op.drop_index('idx_log_timestamp_level', table_name='log_entries')
    op.drop_index('idx_log_request', table_name='log_entries')
    op.drop_index('idx_log_logger_level', table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_index(op.f('ix_api_request_logs_user_id'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_timestamp'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_response_status'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_request_id'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_id'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_client_ip'), table_name='api_request_logs')
    op.drop_index('idx_api_timestamp_status', table_name='api_request_logs')
    op.drop_index('idx_api_path_method', table_name='api_request_logs')
    op.drop_table('api_request_logs')
    # ### end Alembic commands ###