"""Initial tables

Revision ID: f64d40dd0fb0
Revises: 
Create Date: 2025-08-03 15:54:19.466649+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f64d40dd0fb0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('last_successful_fetch', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('configuration', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_table('panel_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('panel_id', sa.String(length=50), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('power_w', sa.Float(), nullable=False),
    sa.Column('voltage_v', sa.Float(), nullable=True),
    sa.Column('current_a', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', 'panel_id', name='uq_panel_reading')
    )
    op.create_index(op.f('ix_panel_readings_id'), 'panel_readings', ['id'], unique=False)
    op.create_index(op.f('ix_panel_readings_panel_id'), 'panel_readings', ['panel_id'], unique=False)
    op.create_index(op.f('ix_panel_readings_timestamp'), 'panel_readings', ['timestamp'], unique=False)
    op.create_table('solar_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('production_kw', sa.Float(), nullable=False),
    sa.Column('consumption_kw', sa.Float(), nullable=False),
    sa.Column('grid_kw', sa.Float(), nullable=False),
    sa.Column('battery_kw', sa.Float(), nullable=True),
    sa.Column('battery_soc', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', name='uq_solar_reading_timestamp')
    )
    op.create_index(op.f('ix_solar_readings_id'), 'solar_readings', ['id'], unique=False)
    op.create_index(op.f('ix_solar_readings_timestamp'), 'solar_readings', ['timestamp'], unique=False)
    op.create_table('system_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_status_id'), 'system_status', ['id'], unique=False)
    op.create_index(op.f('ix_system_status_timestamp'), 'system_status', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_status_timestamp'), table_name='system_status')
    op.drop_index(op.f('ix_system_status_id'), table_name='system_status')
    op.drop_table('system_status')
    op.drop_index(op.f('ix_solar_readings_timestamp'), table_name='solar_readings')
    op.drop_index(op.f('ix_solar_readings_id'), table_name='solar_readings')
    op.drop_table('solar_readings')
    op.drop_index(op.f('ix_panel_readings_timestamp'), table_name='panel_readings')
    op.drop_index(op.f('ix_panel_readings_panel_id'), table_name='panel_readings')
    op.drop_index(op.f('ix_panel_readings_id'), table_name='panel_readings')
    op.drop_table('panel_readings')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
